<?php

/**
 * 关于我们
 * 开发者：浮生若梦
 * 开发时间：2020/9/8
 */

namespace app\index\controller;

use app\BaseController;
use think\facade\Db;
use think\facade\Validate;
use think\facade\View;

class About extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //网站配置
        $config=Db::name('config')->where(['id'=>1])->find();
        View::assign('config',$config);
        //菜单的东西
        //课程体系二级
        $course_type=Db::name('course_type')->where('status','<>',0)->field('id,title')->select();
        View::assign('course_type',$course_type);
        //名师堂二级
        $teach_class=Db::name('teach_class')->where('status','<>',0)->field('id,title')->select();
        View::assign('teach_class',$teach_class);
        View::assign('menu_id',6);
    }

    /**
     * 关于机构
     */
    public function index()
    {
        if(request()->isMobile()) {
            return View::fetch('/about/m_index');
        }else {
            return View::fetch();
        }
    }

    public function news_list()
    {
        $data=request()->param();
        $search=isset($data['search'])?$data['search']:'';
        if($search){
            $where[]=['title','like','%'.$search.'%'];
        }
        $where[]=['status','<>',0];

        if(request()->isMobile()) {
            //轮播
            $banner_list=Db::name('banner')->where('status','<>',0)->where(['type'=>1])->field('id,img_src,title')->select();
            View::assign('banner_list',$banner_list);
            //轮播下图片
            $image_list=Db::name('banner')->where('status','<>',0)->where(['type'=>6])->field('id,img_src,title')->limit(3)->select();
            View::assign('image_list',$image_list);
            //新闻列表
            $news_list=Db::name('news')->where($where)->field('id,title,img_src,desc,publish_time')->order(['publish_time','id'=>'desc'])->paginate(8,true)->each(function($item, $key){
                $item['year'] = date('Y',$item['publish_time']);
                $item['month'] = date('m',$item['publish_time']);
                $item['day'] = date('d',$item['publish_time']);
                return $item;
            });
            $page = $news_list->render();
            View::assign('page',$page);
            View::assign('news_list',$news_list);
            return View::fetch('/about/m_news_list');
        }else {
            //新闻列表
            $news_list=Db::name('news')->where($where)->field('id,title,img_src,desc,publish_time')->order(['publish_time','id'=>'desc'])->paginate(6)->each(function($item, $key){
                $item['year'] = date('Y',$item['publish_time']);
                $item['month'] = date('m',$item['publish_time']);
                $item['day'] = date('d',$item['publish_time']);
                return $item;
            });
            $page = $news_list->render();
            View::assign('page',$page);
            View::assign('news_list',$news_list);
            return View::fetch();
        }
    }

    /**
     * 新闻
     */
    public function detail(){
        $data=request()->param();
        $id=isset($data['id'])?$data['id']:'';
        //新闻详情
        $detail=Db::name('news')->where(['id'=>$id])->find();
        View::assign('detail',$detail);
        //上一个
        $prev_data=Db::name('news')->where('status','<>',0)->where('id','>',$id)->order(['publish_time','id'=>'asc'])->field('id,title,img_src')->find();
        //下一个
        $next_data=Db::name('news')->where('status','<>',0)->where('id','<',$id)->order(['publish_time','id'=>'desc'])->field('id,title,img_src')->find();
        View::assign('prev_data',$prev_data);
        View::assign('next_data',$next_data);
        //最新内容
        $news_list=Db::name('news')->where('status','<>',0)->where('id','<>',$id)->field('id,title,img_src,desc')->order(['publish_time','id'=>'desc'])->limit(8)->select();
        View::assign('news_list',$news_list);
        if(request()->isMobile()) {
            return View::fetch('/about/m_news_detail');
        }else {
            return View::fetch();
        }
    }

}
