<?php

/**
 * 课程体系
 * 开发者：浮生若梦
 * 开发时间：2020/9/8
 */

namespace app\index\controller;

use app\BaseController;
use think\facade\Db;
use think\facade\Validate;
use think\facade\View;

class Course extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //网站配置
        $config=Db::name('config')->where(['id'=>1])->find();
        View::assign('config',$config);
        //菜单的东西
        //课程体系二级
        $course_type=Db::name('course_type')->where('status','<>',0)->field('id,title')->select();
        View::assign('course_type',$course_type);
        //名师堂二级
        $teach_class=Db::name('teach_class')->where('status','<>',0)->field('id,title')->select();
        View::assign('teach_class',$teach_class);
        View::assign('menu_id',2);
    }

    /**
     * 首页
     */
    public function index()
    {
        $data=request()->param();
        $search=isset($data['search'])?$data['search']:'';
        if($search){
            $where[]=['title','like','%'.$search.'%'];
        }
        $type_id=isset($data['type_id'])?$data['type_id']:'';
        $type_title='';
        if($type_id){
            $where[]=['type_id','=',$type_id];
            $type_title=Db::name('course_type')->where(['id'=>$type_id])->value('title');
        }
        $where[]=['status','<>',0];

        if(request()->isMobile()) {
            //轮播
            $banner_list=Db::name('banner')->where('status','<>',0)->where(['type'=>1])->field('id,img_src,title')->select();
            View::assign('banner_list',$banner_list);
            //轮播下图片
            $image_list=Db::name('banner')->where('status','<>',0)->where(['type'=>6])->field('id,img_src,title')->limit(3)->select();
            View::assign('image_list',$image_list);
            //课程列表
            $course_list=Db::name('course')->where($where)->field('id,title,speaker,img_src,desc')->order('id desc')->paginate(8,true);
            $page = $course_list->render();
            View::assign('page',$page);
            View::assign('type_id',$type_id);
            View::assign('type_title',$type_title);
            View::assign('course_list',$course_list);
            return View::fetch('/course/m_index');
        }else {
            //课程列表
            $course_list=Db::name('course')->where($where)->field('id,title,speaker,img_src,desc')->order('id desc')->paginate(8);
            $page = $course_list->render();
            View::assign('page',$page);
            View::assign('type_id',$type_id);
            View::assign('type_title',$type_title);
            View::assign('course_list',$course_list);
            return View::fetch();
        }
    }

    /**
     * 详情
     */
    public function detail(){
        $data=request()->param();
        $id=isset($data['id'])?$data['id']:'';
        //课程详情
        $detail=Db::name('course')->where(['id'=>$id])->find();
        $type_title=Db::name('course_type')->where(['id'=>$detail['type_id']])->value('title');
        View::assign('detail',$detail);
        View::assign('type_title',$type_title);
        //上一个
        $prev_data=Db::name('course')->where('status','<>',0)->where('id','>',$id)->order('id asc')->field('id,title,img_src,speaker')->find();
        //下一个
        $next_data=Db::name('course')->where('status','<>',0)->where('id','<',$id)->order('id desc')->field('id,title,img_src,speaker')->find();
        View::assign('prev_data',$prev_data);
        View::assign('next_data',$next_data);

        //热门课程
        $hot_course_list=Db::name('course')->where('status','<>',0)->where('is_hot','=',1)->where('id','<>',$id)->field('id,title,speaker,img_src,desc')->order('id desc')->limit(4)->select();
        View::assign('hot_course_list',$hot_course_list);
        if(request()->isMobile()) {
            return View::fetch('/course/m_detail');
        }else {
            return View::fetch();
        }
    }

}
