<?php

/**
 * 首页
 * 开发者：浮生若梦
 * 开发时间：2020/9/8
 */

namespace app\index\controller;

use app\BaseController;
use think\facade\Db;
use think\facade\Validate;
use think\facade\View;

class Index extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //网站配置
        $config=Db::name('config')->where(['id'=>1])->find();
        View::assign('config',$config);
        //菜单的东西
        //课程体系二级
        $course_type=Db::name('course_type')->where('status','<>',0)->field('id,title')->select();
        View::assign('course_type',$course_type);
        //名师堂二级
        $teach_class=Db::name('teach_class')->where('status','<>',0)->field('id,title')->select();
        View::assign('teach_class',$teach_class);
    }

    /**
     * 首页
     */
    public function index()
    {
        //轮播
        $banner_list=Db::name('banner')->where('status','<>',0)->where(['type'=>1])->field('id,img_src,title')->select();
        View::assign('banner_list',$banner_list);
        //轮播下图片
        $image_list=Db::name('banner')->where('status','<>',0)->where(['type'=>6])->field('id,img_src,title')->limit(3)->select();
        View::assign('image_list',$image_list);
        //课程列表
        $course_list=Db::name('course')->where('status','<>',0)->field('id,title,speaker,img_src,desc')->order('id desc')->limit(4)->select();
        View::assign('course_list',$course_list);
        //免费直播课
        $free_live=Db::name('free_live')->where('status','<>',0)->field('id,title,speaker,img_src,desc,live_src')->order('id desc')->limit(4)->select();
        View::assign('free_live',$free_live);
        //实力保证
        $strength=Db::name('strength')->where('status','<>',0)->field('id,title,img_src,desc')->select();
        View::assign('strength',$strength);
        //名师堂
        $teach_list=Db::name('teach')->where('status','<>',0)->field('id,title,post,img_src,desc')->order('id desc')->select();

        View::assign('teach_list',$teach_list);
        //遍布数据图
        $spread=Db::name('banner')->where('status','<>',0)->where(['type'=>7])->field('id,img_src,title')->find();
        View::assign('spread',$spread);
        //新闻
        $news_list=Db::name('news')->where('status','<>',0)->field('id,title,img_src,desc,publish_time')->order('publish_time desc')->limit(3)->select()->toArray();
        foreach ($news_list as $k=>$vo){
            $news_list[$k]['year']=date('Y',$vo['publish_time']);
            $news_list[$k]['month']=date('m',$vo['publish_time']);
            $news_list[$k]['day']=date('d',$vo['publish_time']);
        }
        View::assign('news_list',$news_list);
        //战略合作
        $cooper_list=Db::name('cooper')->where('status','<>',0)->field('id,title,img_src')->order('id desc')->select();
        View::assign('cooper_list',$cooper_list);
        View::assign('menu_id',1);
        if(request()->isMobile()) {
            return View::fetch('/index/m_index');
        }else {
            return View::fetch();
        }

    }

    /**
     * 免费学
     */
    public function free_study(){
        if(request()->isAjax()){
            $data=request()->param();
            $validate = Validate::rule([
                'name|姓名' => 'require',
                'telphone|联系方式' => 'require',
//                'course|感兴趣课程' => 'require',
//                'nearby|就近校区' => 'require',
//                'level|目前水平' => 'require',
                'remark|留言' => 'require'
            ]);
            if (!$validate->check($data)) {
                $ajaxarr = ['code' => 100, 'msg' => $validate->getError()];
            } else {
                $data['add_time']=time();
                $data['add_ip']=request()->ip();
                $add_id=Db::name('free_study')->insertGetId($data);
                if($add_id){
                    $ajaxarr=['code'=>200,'msg'=>'提交成功'];
                }else{
                    $ajaxarr=['code'=>400,'msg'=>'提交失败'];
                }
            }
            return json($ajaxarr);
        }else{
            View::assign('menu_id',7);
            if(request()->isMobile()) {
                return View::fetch('/index/m_free_study');
            }else {
                return View::fetch();
            }
        }
    }

    /**
     * 联系我们
     */
    public function contact(){
        View::assign('menu_id',8);
        $background=Db::name('banner')->where('status','<>',0)->where(['type'=>5])->field('id,img_src,title')->order('id desc')->find();
        View::assign('background',$background);
        //联系我们
        $contact_list=Db::name('contact')->where('status','<>',0)->field('id,title,en_title,address,phone,email,post_code,website')->order('id asc')->select();
        View::assign('contact_list',$contact_list);
        if(request()->isMobile()) {
            return View::fetch('/index/m_contact');
        }else {
            return View::fetch();
        }
    }

    /**
     * 战略合作
     */
    public function cooper_detail(){
        $data=request()->param();
        $id=isset($data['id'])?$data['id']:'';
        //新闻详情
        $detail=Db::name('cooper')->where(['id'=>$id])->find();
        View::assign('detail',$detail);
        //上一个
        $prev_data=Db::name('cooper')->where('status','<>',0)->where('id','>',$id)->order('id asc')->field('id,title,img_src')->find();
        //下一个
        $next_data=Db::name('cooper')->where('status','<>',0)->where('id','<',$id)->order('id desc')->field('id,title,img_src')->find();
        View::assign('prev_data',$prev_data);
        View::assign('next_data',$next_data);
        View::assign('menu_id',1);
        if(request()->isMobile()) {
            return View::fetch('/index/m_cooper_detail');
        }else {
            return View::fetch();
        }
    }

}
