<?php

/**
 * 首页
 * 开发者：浮生若梦
 * 开发时间：2020/9/8
 */

namespace app\index\controller;

use app\BaseController;
use think\facade\Db;
use think\facade\Validate;
use think\facade\View;

class Index extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //网站配置

    }

    /**
     * 首页
     */
    public function index()
    {

        header('Location:/admin/login');
        exit;
    }

}
