<?php

/**
 * 实力保证
 * 开发者：浮生若梦
 * 开发时间：2020/9/8
 */

namespace app\index\controller;

use app\BaseController;
use think\facade\Db;
use think\facade\Validate;
use think\facade\View;

class Strength extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //网站配置
        $config=Db::name('config')->where(['id'=>1])->find();
        View::assign('config', $config);
        //菜单的东西
        //课程体系二级
        $course_type=Db::name('course_type')->where('status', '<>', 0)->field('id,title')->select();
        View::assign('course_type', $course_type);
        //名师堂二级
        $teach_class=Db::name('teach_class')->where('status', '<>', 0)->field('id,title')->select();
        View::assign('teach_class', $teach_class);
        View::assign('menu_id', 4);
    }

    /**
     * 首页
     */
    public function index()
    {
        $image=Db::name('banner')->where('status', '<>', 0)->where(['type'=>3])->order('id desc')->field('id,img_src,title')->find();
        View::assign('image', $image);
        //实力保证列表
        $data=request()->param();
        $search=isset($data['search']) ? $data['search'] : '';
        if ($search) {
            $where[]=['title','like','%'.$search.'%'];
        }
        $where[]=['status','<>',0];

        if (request()->isMobile()) {
            //轮播
            $banner_list=Db::name('banner')->where('status', '<>', 0)->where(['type'=>1])->field('id,img_src,title')->select();
            View::assign('banner_list', $banner_list);
            //轮播下图片
            $image_list=Db::name('banner')->where('status', '<>', 0)->where(['type'=>6])->field('id,img_src,title')->limit(3)->select();
            View::assign('image_list', $image_list);
            $strength_list=Db::name('strength')->where($where)->field('id,title,img_src,desc')->order(['sort','id'=>'desc'])->paginate(8, true);
            $page = $strength_list->render();
            View::assign('page', $page);
            View::assign('strength_list', $strength_list);
            return View::fetch('/strength/m_index');
        } else {
            $strength_list=Db::name('strength')->where($where)->field('id,title,img_src,desc')->order(['sort','id'=>'desc'])->paginate(8);
            $page = $strength_list->render();
            View::assign('page', $page);
            View::assign('strength_list', $strength_list);
            return View::fetch();
        }
    }

    /**
     * 详情
     */
    public function detail()
    {
        $data=request()->param();
        $id=isset($data['id']) ? $data['id'] : '';
        //实力保证详情
        $detail=Db::name('strength')->where(['id'=>$id])->find();
        View::assign('detail', $detail);
        //上一个
        $prev_data=Db::name('strength')->where('status', '<>', 0)->where('id', '>', $id)->order(['sort','id'=>'asc'])->field('id,title,img_src')->find();
        //下一个
        $next_data=Db::name('strength')->where('status', '<>', 0)->where('id', '<', $id)->order(['sort','id'=>'desc'])->field('id,title,img_src')->find();
        View::assign('prev_data', $prev_data);
        View::assign('next_data', $next_data);
        if (request()->isMobile()) {
            return View::fetch('/strength/m_detail');
        } else {
            return View::fetch();
        }
    }
}
